---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQx # Base64 encoded value of 'Password1'
---
apiVersion: v1
kind: Pod
metadata:
  name: my-mysql-pod
  labels:
    app: mysql
  namespace: default
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-root-password
          key: MYSQL_ROOT_PASSWORD
    # Add this to ensure a default database is created on startup
    - name: MYSQL_DATABASE
      value: mydatabase # You can change this to any database name you prefer
    ports:
    - containerPort: 3306
      name: mysql-port
    volumeMounts:
    - name: mysql-data
      mountPath: /var/lib/mysql
    # Add a readiness probe to ensure MySQL is truly ready for connections
    readinessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 15 # Give MySQL some time to start up
      periodSeconds: 10 # Check every 10 seconds
      timeoutSeconds: 5 # Timeout after 5 seconds if no connection
      failureThreshold: 3 # After 3 failed attempts, mark as NotReady
  volumes:
  - name: mysql-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-service
  namespace: default
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: mysql-port
  type: NodePort
